### ISSUE TITLE
怎么支持vue-cli3

### ISSUE THREAD

**Issue by luhongmin** [livelyPeng/pl-table#1]
你好，出错的时候，那个配置 怎么在vue.config.js里面配置

**Comment by WhiteGIT** [comment]
是啊，搞了好久没成功。怎么配置vue-cli3 支持 非vue文件中写 jsx语法，或者作者能不能去掉代码中jsx语法

**Comment by livelyPeng** [comment]
首选非VUE文件是啥意思，不在vue中用？ 还有就是这个组件基于vue和element的

**Comment by livelyPeng** [comment]
@luhongmin 具体啥意思 哪里报错了 403802162 加QQ

**Comment by livelyPeng** [comment]
你们的问题已经解决啦，看文档，最新版本

**Comment by WhiteGIT** [comment]
大佬这还是报错~
` in F:/Git/scm-web/node_modules/pl-table/package/src/style.css

Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: **No PostCSS Config found in: F:\Git\scm-web\node_modules\pl-table\package\src**
    at config.search.then (F:\Git\scm-web\src\main\resources\source\node_modules\postcss-load-config\src\index.js:91:15)

 @ F:/Git/scm-web/node_modules/pl-table/package/src/style.css 4:14-224 14:3-18:5 15:22-232
 @ F:/Git/scm-web/node_modules/pl-table/package/index.js
 @ F:/Git/scm-web/node_modules/pl-table/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://10.117.49.48:9527/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in F:/Git/scm-web/node_modules/pl-table/themes/plTableStyle.less

Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: **No PostCSS Config found in: F:\Git\scm-web\node_modules\pl-table\themes**
    at config.search.then (F:\Git\scm-web\src\main\resources\source\node_modules\postcss-load-config\src\index.js:91:15)`

**Comment by livelyPeng** [comment]
@WhiteGIT 你加我Q 403802162  你不是新版本

**Comment by livelyPeng** [comment]
@WhiteGIT 你这个是不支持CSS，你得去webpack里面配置啊 比如 css less sass

**Comment by livelyPeng** [comment]
@WhiteGIT {
        test: /\.css$/,
        use: [{
          loader: process.env.NODE_ENV === 'production' ? MiniCssExtractPlugin.loader : 'vue-style-loader',
        }, {
          loader: 'css-loader',
          options: {
            sourceMap: process.env.NODE_ENV === 'production' ? config.build.productionSourceMap : config.dev.cssSourceMap
          }
        }]
      }

**Comment by WhiteGIT** [comment]
你QQ 加不上，要验证，更新最新版本完，用你的例子 数据出不来

**Comment by livelyPeng** [comment]
@WhiteGIT 验证答案就是 pl

**Comment by liuhuaxia** [comment]
正常加载，但是不会虚拟加载怎么搞 use-virtua没有用

**Comment by livelyPeng** [comment]
加QQ




------------------ 原始邮件 ------------------
发件人: "liuhx"<notifications@github.com>; 
发送时间: 2019年10月15日(星期二) 下午4:51
收件人: "livelyPeng/pl-table"<pl-table@noreply.github.com>; 
抄送: "Simple love"<403802162@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [livelyPeng/pl-table] 怎么支持vue-cli3 (#1)




正常加载，但是不会虚拟加载怎么搞 use-virtua没有用

**Comment by livelyPeng** [comment]
@luhongmin 是use-virtual 不是use-virtua   你有啥问题加QQ 403802162
